<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sameer" ignored="0" name="Test 1" tests="4" failures="1" timestamp="2023-03-20T18:12:01 IST" time="0.052" errors="0">
  <testcase name="Test1" time="0.008" classname="runtimeRetryFailedTc.Test001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="runtimeRetryFailedTc.Test001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="runtimeRetryFailedTc.Test001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runtimeRetryFailedTc.Test001.Test1(Test001.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="runtimeRetryFailedTc.Test001"/>
</testsuite> <!-- Test 1 -->
